#!/usr/bin/env python3
"""
Hybrid Stress Test Runner

Combines the most powerful SMT optimizations (trace_attr_aware, per-class bounds, 
metamodel slicing) from run_all_stress_report.py with the CEGAR refinement loop 
from run_cegar.py to validate counterexamples.
"""
from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from dsltrans.parser import parse_dsltrans_file
from dsltrans.abstraction import AbstractionPolicy, synthesize_abstract_spec_for_property
from dsltrans.inheritance_flattening import flatten_spec_for_property, lift_counterexample
from dsltrans.cutoff import (
    check_fragment, build_fragment, get_relevant_rules, 
    layer_indices_for_rules, minimal_satisfying_layer_indices, compute_cutoff_bound
)
from dsltrans.smt_direct import SMTDirectConfig, SMTDirectVerifier
from run_cegar import (
    MAX_FALLBACK_K,
    _cegar_confirm_violated,
    _verify_with_fragment_isolated,
    _print_counterexample,
)

EXAMPLES_DIR = Path(__file__).resolve().parent.parent / "examples"
DOCS_DIR = Path(__file__).resolve().parent.parent / "docs" / "evaluation"
OUT_PATH = DOCS_DIR / "hybrid_cegar_stress_results.md"

def write_results_md(rows: list[dict], dependency_mode: str, out_path: Path | None = None) -> None:
    path = out_path or OUT_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Hybrid CEGAR Stress Test Results",
        "",
        "Generated by `run_hybrid_cegar_stress.py`. Uses minimal fragment + `trace_attr_aware` + CEGAR for counterexamples.",
        "",
        "| Spec | Property | K | Bound used | Result | Time (ms) | Complete | CEGAR Iters | Notes |",
        "|------|----------|---|------------|--------|-----------|----------|-------------|-------|",
    ]
    for r in rows:
        k = r.get("K") if r.get("K") is not None else "-"
        cegar_iters = r.get("cegar_iters", 0)
        note = str(r.get("message", "")).replace("|", "\\|")
        lines.append(
            f"| {r['spec']} | {r['property']} | {k} | {r['bound_used']} | {r['result']} | {r['time_ms']} | {r['is_complete']} | {cegar_iters} | {note} |"
        )
    lines.extend(["", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def _verify_property_hybrid_atomic(
    spec,
    prop,
    *,
    dependency_mode: str = "trace_attr_aware",
    timeout_ms: int = 600_000,
    fallback_k_cap: int = MAX_FALLBACK_K,
) -> dict:
    if not spec.transformations:
        raise ValueError("Spec has no transformations")
    full_trans = spec.transformations[0]

    in_frag, violations = check_fragment(full_trans, prop)
    if not in_frag:
        return {
            "property": prop.name,
            "skipped": True,
            "skip_reason": "not_in_fragment",
            "fragment_violations": list(violations),
        }

    baseline_layers = layer_indices_for_rules(full_trans, get_relevant_rules(full_trans, prop))
    min_layers = minimal_satisfying_layer_indices(full_trans, prop)
    # Defensive fallback: some valid properties can yield an empty minimal set in
    # aggressive pruning paths; use baseline layers instead of crashing.
    if not min_layers:
        min_layers = baseline_layers or list(range(len(full_trans.layers)))
    min_frag = build_fragment(full_trans, min_layers)
    K_min = compute_cutoff_bound(
        min_frag,
        prop,
        use_reduced_k=True,
        dependency_mode=dependency_mode,
    )

    res, used_strict_confirm, _ = _verify_with_fragment_isolated(
        spec=spec,
        prop=prop,
        fragment_trans=min_frag,
        K=K_min,
        timeout_ms=timeout_ms,
        per_class_heuristic_confirm=True,
        strict_per_class_bounds=True,
    )

    cegar_iters = 0
    final_k = K_min
    cegar_status: str | None = None
    violation_confirmed = min_layers == baseline_layers

    if res.result.name == "VIOLATED" and min_layers != baseline_layers:
        res, refined_layers, refined_k, cegar_status = _cegar_confirm_violated(
            spec=spec,
            prop=prop,
            full_trans=full_trans,
            initial_res=res,
            initial_layers=min_layers,
            initial_k=K_min,
            baseline_layers=baseline_layers,
            dependency_mode=dependency_mode,
            timeout_ms=timeout_ms,
            relax_containment=False,
            per_class_heuristic_confirm=True,
            strict_per_class_bounds=True,
        )
        final_k = refined_k
        cegar_iters = len(refined_layers) - len(min_layers)

        if cegar_status == "baseline_reached" and res.result.name == "VIOLATED":
            violation_confirmed = True
        if cegar_status == "certified_no_omitted_match" and res.result.name == "VIOLATED":
            violation_confirmed = True

        if cegar_status in ("baseline_reached", "refined_k_too_large") and res.result.name == "VIOLATED":
            if not baseline_layers:
                is_complete = violation_confirmed or used_strict_confirm
                return {
                    "property": prop.name,
                    "skipped": False,
                    "K": final_k,
                    "bound_used": res.bound_used,
                    "result": res.result.name,
                    "time_ms": round(res.time_ms, 1),
                    "is_complete": is_complete,
                    "cegar_iters": cegar_iters,
                    "counterexample": getattr(res, "counterexample", None),
                    "message": getattr(res, "message", ""),
                }
            baseline_frag = build_fragment(full_trans, baseline_layers)
            K_base = compute_cutoff_bound(
                baseline_frag,
                prop,
                use_reduced_k=True,
                dependency_mode=dependency_mode,
            )
            if K_base <= fallback_k_cap:
                res, used_strict_confirm, _ = _verify_with_fragment_isolated(
                    spec=spec,
                    prop=prop,
                    fragment_trans=baseline_frag,
                    K=K_base,
                    timeout_ms=timeout_ms,
                    per_class_heuristic_confirm=True,
                    strict_per_class_bounds=True,
                )
                final_k = K_base
                if res.result.name == "VIOLATED":
                    violation_confirmed = True

    message = getattr(res, "message", "")
    result_name = res.result.name
    if result_name == "VIOLATED" and not violation_confirmed:
        result_name = "UNKNOWN"
        detail = (
            f"minimal-fragment violation remained unconfirmed"
            f"{f' after CEGAR status {cegar_status}' if cegar_status else ''}"
        )
        if baseline_layers:
            baseline_frag = build_fragment(full_trans, baseline_layers)
            K_base = compute_cutoff_bound(
                baseline_frag,
                prop,
                use_reduced_k=True,
                dependency_mode=dependency_mode,
            )
            if K_base > fallback_k_cap:
                detail = f"{detail}; baseline confirmation requires K={K_base} > cap {fallback_k_cap}"
        message = f"Unconfirmed violation: {detail}."

    is_complete = violation_confirmed or (result_name == "HOLDS" and used_strict_confirm)
    return {
        "property": prop.name,
        "skipped": False,
        "K": final_k,
        "bound_used": res.bound_used,
        "result": result_name,
        "time_ms": round(res.time_ms, 1),
        "is_complete": is_complete,
        "cegar_iters": cegar_iters,
        "counterexample": getattr(res, "counterexample", None),
        "message": message,
    }


def verify_property_hybrid(
    spec,
    prop,
    *,
    dependency_mode: str = "trace_attr_aware",
    timeout_ms: int = 600_000,
    fallback_k_cap: int = MAX_FALLBACK_K,
    abstraction_policy: AbstractionPolicy | None = None,
) -> dict:
    if abstraction_policy is not None:
        abstract_result = synthesize_abstract_spec_for_property(spec, abstraction_policy, prop.name)
        spec = abstract_result.abstract_spec
        prop = spec.properties[0]

    flat_bundle = flatten_spec_for_property(spec, prop)
    if not flat_bundle.applied:
        return _verify_property_hybrid_atomic(
            spec,
            prop,
            dependency_mode=dependency_mode,
            timeout_ms=timeout_ms,
            fallback_k_cap=fallback_k_cap,
        )

    full_trans = spec.transformations[0]
    in_frag, violations = check_fragment(full_trans, prop)
    if not in_frag:
        return {
            "property": prop.name,
            "skipped": True,
            "skip_reason": "not_in_fragment",
            "fragment_violations": list(violations),
        }

    baseline_layers_orig = layer_indices_for_rules(full_trans, get_relevant_rules(full_trans, prop))
    # Guard against aggressive relevance pruning that may yield no layers for
    # some properties (e.g. pure negative checks). Fallback to atomic path.
    if not baseline_layers_orig:
        return _verify_property_hybrid_atomic(
            spec,
            prop,
            dependency_mode=dependency_mode,
            timeout_ms=timeout_ms,
            fallback_k_cap=fallback_k_cap,
        )
    baseline_frag_orig = build_fragment(full_trans, baseline_layers_orig)
    baseline_spec_orig = type(spec)(
        metamodels=spec.metamodels,
        transformations=(baseline_frag_orig,),
        properties=(prop,),
    )
    flat_rows = []
    flat_baseline_bundle = flatten_spec_for_property(baseline_spec_orig, prop)
    # If property-guided pruning collapses every variant to zero layers, fall
    # back to the atomic path (which still benefits from internal flattening in
    # SMTDirectVerifier) instead of raising on empty fragments.
    if any(
        (not v.spec.transformations) or (not v.spec.transformations[0].layers)
        for v in flat_baseline_bundle.variants
    ):
        return _verify_property_hybrid_atomic(
            spec,
            prop,
            dependency_mode=dependency_mode,
            timeout_ms=timeout_ms,
        )
    for variant in flat_baseline_bundle.variants:
        flat_spec = variant.spec
        flat_prop = variant.property
        flat_full_trans = flat_spec.transformations[0]
        flat_baseline_layers = list(range(len(flat_full_trans.layers)))
        in_frag, violations = check_fragment(flat_full_trans, flat_prop)
        if not in_frag:
            flat_rows.append(
                {
                    "property": prop.name,
                    "skipped": True,
                    "skip_reason": "not_in_fragment",
                    "fragment_violations": list(violations),
                }
            )
            continue

        min_layers = minimal_satisfying_layer_indices(flat_full_trans, flat_prop)
        # Defensive fallback matching the atomic path: avoid empty fragment crash.
        if not min_layers:
            min_layers = flat_baseline_layers or list(range(len(flat_full_trans.layers)))
        min_frag = build_fragment(flat_full_trans, min_layers)
        K_min = compute_cutoff_bound(
            min_frag,
            flat_prop,
            use_reduced_k=True,
            dependency_mode=dependency_mode,
        )

        res, used_strict_confirm, _ = _verify_with_fragment_isolated(
            spec=flat_spec,
            prop=flat_prop,
            fragment_trans=min_frag,
            K=K_min,
            timeout_ms=timeout_ms,
            per_class_heuristic_confirm=True,
            strict_per_class_bounds=True,
        )

        cegar_iters = 0
        final_k = K_min
        cegar_status: str | None = None
        violation_confirmed = min_layers == flat_baseline_layers

        if res.result.name == "VIOLATED" and min_layers != flat_baseline_layers:
            res, refined_layers, refined_k, cegar_status = _cegar_confirm_violated(
                spec=flat_spec,
                prop=flat_prop,
                full_trans=flat_full_trans,
                initial_res=res,
                initial_layers=min_layers,
                initial_k=K_min,
                baseline_layers=flat_baseline_layers,
                dependency_mode=dependency_mode,
                timeout_ms=timeout_ms,
                relax_containment=False,
                per_class_heuristic_confirm=True,
                strict_per_class_bounds=True,
            )
            final_k = refined_k
            cegar_iters = len(refined_layers) - len(min_layers)

            if cegar_status == "baseline_reached" and res.result.name == "VIOLATED":
                violation_confirmed = True
            if cegar_status == "certified_no_omitted_match" and res.result.name == "VIOLATED":
                violation_confirmed = True

            if cegar_status in ("baseline_reached", "refined_k_too_large") and res.result.name == "VIOLATED":
                if flat_baseline_layers:
                    K_base = compute_cutoff_bound(
                        flat_full_trans,
                        flat_prop,
                        use_reduced_k=True,
                        dependency_mode=dependency_mode,
                    )
                    if K_base <= fallback_k_cap:
                        res, used_strict_confirm, _ = _verify_with_fragment_isolated(
                            spec=flat_spec,
                            prop=flat_prop,
                            fragment_trans=flat_full_trans,
                            K=K_base,
                            timeout_ms=timeout_ms,
                            per_class_heuristic_confirm=True,
                            strict_per_class_bounds=True,
                        )
                        final_k = K_base
                        if res.result.name == "VIOLATED":
                            violation_confirmed = True

        message = getattr(res, "message", "")
        result_name = res.result.name
        if result_name == "VIOLATED" and not violation_confirmed:
            result_name = "UNKNOWN"
            detail = (
                f"minimal-fragment violation remained unconfirmed"
                f"{f' after CEGAR status {cegar_status}' if cegar_status else ''}"
            )
            K_base = compute_cutoff_bound(
                flat_full_trans,
                flat_prop,
                use_reduced_k=True,
                dependency_mode=dependency_mode,
            )
            if K_base > fallback_k_cap:
                detail = f"{detail}; baseline confirmation requires K={K_base} > cap {fallback_k_cap}"
            message = f"Unconfirmed violation: {detail}."

        flat_rows.append(
            {
                "property": flat_prop.name,
                "skipped": False,
                "K": final_k,
                "bound_used": res.bound_used,
                "result": result_name,
                "time_ms": round(res.time_ms, 1),
                "is_complete": violation_confirmed or (result_name == "HOLDS" and used_strict_confirm),
                "cegar_iters": cegar_iters,
                "counterexample": getattr(res, "counterexample", None),
                "message": message,
            }
        )

    if any(r.get("skipped") for r in flat_rows):
        skipped = next(r for r in flat_rows if r.get("skipped"))
        return {
            "property": prop.name,
            "skipped": True,
            "skip_reason": skipped.get("skip_reason", "flattened_variant_skipped"),
            "fragment_violations": skipped.get("fragment_violations", []),
        }

    total_time = round(sum(float(r.get("time_ms", 0.0)) for r in flat_rows), 1)
    max_k = max(int(r.get("K") or 0) for r in flat_rows) if flat_rows else None
    max_bound = max(int(r.get("bound_used") or 0) for r in flat_rows) if flat_rows else 0
    total_cegar = sum(int(r.get("cegar_iters", 0)) for r in flat_rows)

    violated = next((r for r in flat_rows if r.get("result") == "VIOLATED"), None)
    if violated is not None:
        return {
            "property": prop.name,
            "skipped": False,
            "K": violated.get("K", max_k),
            "bound_used": violated.get("bound_used", max_bound),
            "result": "VIOLATED",
            "time_ms": total_time,
            "is_complete": bool(violated.get("is_complete", False)),
            "cegar_iters": total_cegar,
            "counterexample": lift_counterexample(
                violated.get("counterexample"),
                original_transformation=flat_baseline_bundle.original_transformation,
                rule_name_map=flat_baseline_bundle.rule_name_map,
                assoc_origin_map=flat_baseline_bundle.assoc_origin_map,
            ),
            "message": violated.get("message", ""),
        }

    unknown = next((r for r in flat_rows if r.get("result") == "UNKNOWN"), None)
    if unknown is not None:
        return {
            "property": prop.name,
            "skipped": False,
            "K": max_k,
            "bound_used": max_bound,
            "result": "UNKNOWN",
            "time_ms": total_time,
            "is_complete": False,
            "cegar_iters": total_cegar,
            "counterexample": None,
            "message": unknown.get("message", "one or more flattened variants were inconclusive"),
        }

    return {
        "property": prop.name,
        "skipped": False,
        "K": max_k,
        "bound_used": max_bound,
        "result": "HOLDS",
        "time_ms": total_time,
        "is_complete": all(bool(r.get("is_complete", False)) for r in flat_rows),
        "cegar_iters": total_cegar,
        "counterexample": None,
        "message": "",
    }

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--timeout", type=int, default=600_000)
    parser.add_argument("--dependency-mode", default="trace_attr_aware")
    parser.add_argument("--fallback-k-cap", type=int, default=MAX_FALLBACK_K)
    parser.add_argument("--specs", nargs="*", default=None)
    parser.add_argument("--out", type=str, default=None, help="Output markdown path. Default: docs/evaluation/hybrid_cegar_stress_results.md")
    args = parser.parse_args()

    all_rows = []
    out_path = Path(args.out) if args.out else None
    
    if args.specs:
        specs_to_run = args.specs
    else:
        specs_to_run = [p.name for p in EXAMPLES_DIR.glob("*_concrete.dslt")]

    print(f"Running hybrid CEGAR verification (dependency_mode={args.dependency_mode})...", flush=True)
    
    for spec_name in specs_to_run:
        path = EXAMPLES_DIR / spec_name
        if not path.exists():
            print(f"  Skip (not found): {spec_name}", flush=True)
            continue
        try:
            spec = parse_dsltrans_file(path)
            if not spec.transformations or not spec.properties:
                continue
            full_trans = spec.transformations[0]
            
            for prop in spec.properties:
                outcome = verify_property_hybrid(
                    spec,
                    prop,
                    dependency_mode=args.dependency_mode,
                    timeout_ms=args.timeout,
                    fallback_k_cap=args.fallback_k_cap,
                )
                if outcome.get("skipped"):
                    violations = outcome.get("fragment_violations", [])
                    print(f"  {spec_name} / {prop.name}: Not in fragment! Violations: {violations}", flush=True)
                    continue
                row = {
                    "spec": spec_name,
                    "property": prop.name,
                    "K": outcome["K"],
                    "bound_used": outcome["bound_used"],
                    "result": outcome["result"],
                    "time_ms": outcome["time_ms"],
                    "is_complete": outcome["is_complete"],
                    "cegar_iters": outcome["cegar_iters"],
                    "message": outcome.get("message", ""),
                }
                all_rows.append(row)
                print(
                    f"  {spec_name} / {prop.name} (K={outcome['K']}) ... {outcome['result']} ({outcome['time_ms']:.0f} ms)",
                    flush=True,
                )
                
                write_results_md(all_rows, args.dependency_mode, out_path=out_path)
                
        except Exception as e:
            import traceback
            traceback.print_exc()
            print(f"  {spec_name}: ERROR {e}", flush=True)

    holds = sum(1 for r in all_rows if r["result"] == "HOLDS")
    violated = sum(1 for r in all_rows if r["result"] == "VIOLATED")
    print(f"Total: {len(all_rows)} | HOLDS: {holds} | VIOLATED: {violated}", flush=True)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
